version: '3'
networks:
  reunionou.net:
    driver: bridge
services:
#####################################################
# API SERVICES
#####################################################

#REUNION WEBAPP
  api.reunion.app:
    image: 'canals/php:latest'
    environment:
      - VHOST_HOSTNAME=api.reunionou.app
      - VHOST_DOCROOT=/var/www/public
    ports:
      - '19180:80'
      - '19100:800'
    volumes:
      - './reunionou.app/public:/var/www/public'
      - './reunionou.app/src:/var/www/src'
    working_dir: /var/www/src
    networks:
      - reunionou.net
    depends_on:
      - mysql.reunionou



  #Mobile
  api.reunion.mobile:
    image: 'canals/php:latest'
    environment:
      - VHOST_HOSTNAME=api.reunionou.mobile
      - VHOST_DOCROOT=/var/www/public
    ports:
      - '19280:80'
      - '19200:820'
    volumes:
      - './reunionou.mobile_service/public:/var/www/public'
      - './reunionou.mobile_service/src:/var/www/src'
    working_dir: /var/www/src
    networks:
      - reunionou.net
    depends_on:
      - mysql.reunionou

  
  #backoffice

  api.reunion.back:
    image: 'canals/php:latest'
    environment:
      - VHOST_HOSTNAME=api.reunionou.back
      - VHOST_DOCROOT=/var/www/public
    ports:
      - '19380:80'
      - '19300:830'
    volumes:
      - './reunionou.back_service/public:/var/www/public'
      - './reunionou.back_service/src:/var/www/src'
    working_dir: /var/www/src
    networks:
      - reunionou.net
    depends_on:
      - mysql.reunionou



  #Mysql
  mysql.reunionou:
    image: 'mariadb:latest'
    command: '--default-reunionou-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    environment:
      - MYSQL_ROOT_PASSWORD=comroot
      - MYSQL_USER=reunionou_reunion
      - MYSQL_PASSWORD=reunionou_reunion
      - MYSQL_DATABASE=reunionou_reunion
    ports:
      - '3407:3406'
    networks:
      - reunionou.net
    volumes:
      - './reunionou_service/sql:/var/sql'



  #BDD

  adminer:
    image: adminer
    ports:
      - '8080:8080'
    networks:
      - reunionou.net
